# -*- coding: utf-8 -*-
"""RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5tm2eiebIFp6ArUPej8ir0TOxIQNmHw

### RAG Pipeline - Data Ingestion to Vector DB Pipeline
"""

!pip install langchain langchain-core langchain-community pypdf pymupdf

!pip install langchain-community
import os

os.makedirs("/content/data", exist_ok=True)
from langchain_community.document_loaders import PyPDFLoader, PyMuPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pathlib import Path

### Fun to Read all the pdf's inside the directory
def process_all_pdfs(pdf_directory):

    all_pages = []

    pdf_dir = Path(pdf_directory)   # gives Path-object
    pdf_files = list(pdf_dir.glob("**/*.pdf"))   # list of Path-objects for all pdf-files.

    print(f"Found {len(pdf_files)} PDF files in Folder, going to process these..")


    for p in pdf_files:
            loader = PyPDFLoader(str(p))
            pages_doc_ds = loader.load() # load all pages in Document-DS of p PDFfile (matadata + page content)

            # Add extra information to metadata
            for page in pages_doc_ds:
                page.metadata['source_file'] = p.name
                page.metadata['file_type'] = 'pdf'

            all_pages.extend(pages_doc_ds)

            print(f"  ✓ Loaded {len(pages_doc_ds)} pages")



    print(f"\nTotal documents loaded: {len(all_pages)}")
    return all_pages




all_pdf_documents = process_all_pdfs("/content/data")    # calling this fun

"""1 document  =  1 page of 1 PDF"""

### Fun for Text splitting to create Chunks

def create_chunk (documents,chunk_size=1000,chunk_overlap=200):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        length_function=len,
        separators=["\n\n", "\n", " ", ""]
    )

    chunks = text_splitter.split_documents(documents)
    print(f"Split {len(documents)} documents into {len(chunks)} chunks")


    return chunks

chunks=create_chunk(all_pdf_documents)
print(chunks)

"""### Use ChromaDB for embeddings and vector store:"""

!pip install chromadb
import chromadb

clint = chromadb.Client()
collection = clint.get_or_create_collection("docs")

!pip install sentence_transformers
from sentence_transformers import SentenceTransformer

m = SentenceTransformer('all-MiniLM-L6-v2')

i = 1
for c in chunks:
  collection.add(
      documents=[c.page_content],
      embeddings=[m.encode(c.page_content)],
      metadatas=[c.metadata],
      ids=[str(i)]
  )
  i=i+1

collection.peek()

# fun for result simmlear to quary

def simm(q, k):
  q_emb = m.encode(q)
  result = collection.query(
      query_embeddings= q_emb,
      n_results= k
  )
  return result

a = simm("what is crc?", 2)
a['documents']

!pip install openai
!pip install langchain-openai langchain

#import os
#os.environ["XAI_API_KEY"] = "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"

from openai import OpenAI
clint = OpenAI(
    api_key = "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",
    base_url= "https://api.groq.com/openai/v1"
)

def chat_with_llm(q, c, m="llama-3.1-8b-instant"):
  prompt = f"""
          Use the following context to answer the question concisely.
          context : {c['documents']}
          question : {q}
          """


  responce = clint.chat.completions.create(
      model = m,
      messages=[{
          "role": "user",
          "content": prompt
      }]
  )

  return responce.choices[0].message.content

# input
que = input("Hello! How may I help you? :  ")

context = simm(que, 2)
print(chat_with_llm(que,context))

